site:
  title: Monyfi AAA
  url: https://tyoshitha95-oss.github.io/antora-docs
  start_page: project-name::Dialog/DialogStart.adoc
content:
  sources:
    - url: https://github.com/tyoshitha95-oss/antora-docs.git
      branches:
        - master
        - v1.0
        - v2.0
        - v3.0
        - v4.0
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    kroki-server-url: https://kroki.io