= Test Case: ENT1 - Framed IP is sent by the SMF

== Description

the Framed IP Address value is picked directly from the incoming Access-Request packet sent by the SMF — the AAA server simply reads it from the request and echoes it back in the Access-Accept response.

API field                       Value

Username                    dialog
VRF name                    ltel2fr2
loopback name               loopback
APN                         ltel2fr2
MSISDN                      940812404795
user group                  ENT1
Password                    dialog123

Request packet

echo -e 'Packet-Type = Access-Request\nUser-Name = "dialog"\nUser-Password = "dialog123"\nClient-Id = 10.174.226.80\nUser-Service-Type = Framed-User\nFramed-Protocol = 7\nCalled-Station-Id = "test"\nCalling-Station-Id = "94812404110"\nAcct-Multi-Session-Id = "01c2dd37"\nFramed-Address = 198.23.89.12\nEvent-Timestamp = 1745882480\nNAS-Port-Type = Virtual' | radclient -x 10.58.167.86 auth mysecret		

Accounting start packet

echo -e 'Acct-Status-Type = Start\nAcct-Link-Count = 1\nEvent-Timestamp = 1745895750\nAcct-Authentic = RADIUS\nAcct-Delay-Time = 0\nAcct-Multi-Session-Id = "3dc2e53f"\nCalling-Station-Id = "94812404106"\nFramed-Address = 10.164.1.74\nAcct-Session-Id = "ca45c4b03dc2e53f"\nFramed-Protocol = 7\nCalled-Station-Id = "test"\nUser-Name = "dialog"\nUser-Service-Type = Framed-User\nNAS-Port-Type = Virtual' | radclient -x 10.58.167.86 acct mysecret		

Accounting interim update

echo -e 'Acct-Status-Type =  Interim-Update\nAcct-Input-Octets = 735035\nAcct-Output-Octets = 3451792\nAcct-Input-Packets = 5830\nAcct-Output-Packets = 5473\nAcct-Link-Count = 1\nEvent-Timestamp = 1745896478\nAcct-Authentic = RADIUS\nAcct-Delay-Time = 0\nAcct-Session-Time = 727\nAcct-Multi-Session-Id = "3dc2e53f"\nCalling-Station-Id = "94812404106"\nFramed-Address = 10.164.1.74\nAcct-Session-Id = "ca45c4b03dc2e53f"\nFramed-Protocol = 7\nCalled-Station-Id = "test"\nUser-Name = "dialog"\nUser-Service-Type = Framed-User\nNAS-Port-Type = Virtual' | radclient -x 10.58.167.86 acct mysecret		

Accounting Stop

echo -e 'Acct-Status-Type =  stop\nAcct-Input-Octets = 735035\nAcct-Output-Octets = 3451792\nAcct-Input-Packets = 5830\nAcct-Output-Packets = 5473\nAcct-Link-Count = 1\nEvent-Timestamp = 1745896478\nAcct-Authentic = RADIUS\nAcct-Delay-Time = 0\nAcct-Session-Time = 727\nAcct-Multi-Session-Id = "3dc2e53f"\nCalling-Station-Id = "94812404106"\nFramed-Address = 10.164.1.74\nAcct-Session-Id = "ca45c4b03dc2e53f"\nFramed-Protocol = 7\nCalled-Station-Id = "test"\nUser-Name = "dialog"\nUser-Service-Type = Framed-User\nNAS-Port-Type = Virtual' | radclient -x 10.58.167.86 acct mysecret		
